trigger:
  branchs:
    include:
      - main

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  static_webapp_token: $(AZURE_STATIC_WEBAPP_TOKEN)

stages:
  - stage: Deploy
    displayName: 'Deploy to Azure'
    jobs:
      - job: Deploy
        displayName: 'Static Deploy'
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Artifacts'
            inputs: 
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzurestaticWebApp@0
            displayName: 'Deploy into Azure'
            inputs:
              app_location: '$(System.ArtifactsDirectory/drop)'
              azure_static_web_apps_api_token: $(static_webapp_token)