trigger:
  branchs:
    include:
      - main
      - staging
      - developer
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dotnetVersion: '6.0.x'
  azureSubscription: 'AzureSubscription'
  webAppName: 'WebApi'

stages:
  - stage: Build
    displayName: 'Build e Tests'
    jobs:
      - job: Build
        displayName: 'Compile e Test .NET Core'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK $(dotnetVersion)'
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - script: dotnet restore
            displayName: 'Restore Dependencies'

          - script: dotnet build --configuration $(buildConfiguration) --no-restore
            displayName: 'Compile App'

          - script: dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
            displayName: 'Exec Unit Testes'

          - script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
            displayName: 'Publish Artifacts'

          - task: PublishBuildArtifacts@1
            displayName: 'Save Artifacts'
            inputs:
              pathToPublish: $(Build.ArtifactStagingDirectory)
              artifactName: drop
