trigger:
  branchs:
    include:
      - main
      - staging
      - developer
      - feature/*
  paths:
    include:
      - src/

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '18.x'
  build_configuration: 'production'
  angular_project: 'angular-ui'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js $(node_version)'
    inputs:
      versionSpec: $(node_version)

  - script: npm ci
    displayName: "Install dependencies"

  - script: npm run lint
    displayName: "Exec Linter"

  - script: npm run test -- --watch=false --browsers=ChromeHeadless
    displayName: "Exec Unit Tests"

  - script: npm run build
    displayName: "Compile"

  - task: CopyFiles@2
    displayName: 'Copy files to artifacts folder'
    inputs:
      SourceFolder: 'dist/$(angular_project)' 
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Public Artifacts'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'drop'

